import type { Role, RoleConfig } from "@/types/roles";

export const roleConfigs: Record<Role, RoleConfig> = {
  staffelleitung: {
    id: "staffelleitung",
    label: "Staffelleitung",
    subtitle: "DVV · Verbandsliga Nord",
    userName: "Stefan Meier",
    initials: "SM",
    gradient: "from-accent to-[#6D28D9]",
    defaultScreen: "dashboard",
    navSections: [
      {
        label: "",
        items: [
          { id: "dashboard", label: "Dashboard", icon: "grid" },
          { id: "mail", label: "Mail", icon: "mail" },
          { id: "kalender", label: "Kalender", icon: "calendar" },
          { id: "kontakte", label: "Kontakte", icon: "book-open" },
        ],
      },
      {
        label: "Spielbetrieb",
        items: [
          { id: "spieltag", label: "Ligenübersicht", icon: "scan" },
          { id: "ligen", label: "Meine Ligen", icon: "star" },
          { id: "mannschaft", label: "Mannschaften meiner Ligen", icon: "users" },
          { id: "heimspieltermine", label: "Heimspieltermine", icon: "calendar-home" },
          { id: "spielplan-verwaltung", label: "Spielplan", icon: "calendar-edit" },
          { id: "live-ticker", label: "Live-Ticker", icon: "volleyball" },
          { id: "sr-ansetzung", label: "SR-Ansetzungen", badge: 3, icon: "whistle" },
          { id: "matchday-master", label: "MatchDay Master", icon: "shield-check" },
        ],
      },
      {
        label: "Verband",
        items: [
          { id: "alle-ligen", label: "Alle Ligen", icon: "org-tree" },
          { id: "alle-mannschaften", label: "Alle Mannschaften", icon: "layers" },
          { id: "statistik", label: "Statistiken", icon: "pie-chart" },
          { id: "strafen", label: "Meine Strafbescheide", badge: 1, icon: "alert" },
          { id: "support-center", label: "Hilfe & Support", icon: "info" },
        ],
      },
    ],
    breadcrumbs: {
      dashboard: ["DVV", "Dashboard"],
      mail: ["DVV", "Mail"],
      kalender: ["DVV", "Kalender"],
      kontakte: ["DVV", "Kontakte"],
      ligen: ["DVV", "Meine Ligen"],
      mannschaft: ["DVV", "Mannschaften meiner Ligen"],
      "alle-ligen": ["DVV", "Alle Ligen"],
      "alle-mannschaften": ["DVV", "Alle Mannschaften"],
      spieltag: ["DVV", "Ligenübersicht"],
      heimspieltermine: ["DVV", "Heimspieltermine"],
      statistik: ["DVV", "Statistiken"],
      veranstaltungen: ["DVV", "Veranstaltungen"],
      veranstaltung: ["DVV", "Veranstaltung erstellen"],
      rechnungen: ["DVV", "Rechnungen"],
      strafen: ["DVV", "Meine Strafbescheide"],
      "spielplan-verwaltung": ["DVV", "Spielplan-Verwaltung"],
      "live-ticker": ["DVV", "Live-Ticker"],
      "sr-ansetzung": ["DVV", "SR-Ansetzungen"],
    },
    newModalItems: [
      { icon: "calendar", name: "Spieltag verwalten", desc: "Spielplan bearbeiten, Verlegungen", border: "border-l-accent", nav: "spieltag" },
      { icon: "clipboard", name: "Mannschaftsmeldung", desc: "Meldungen prüfen & bestätigen", border: "border-l-green", nav: "mannschaft", action: "open-neue-meldung" },
      { icon: "volleyball", name: "Turnier erstellen", desc: "Turnierbaum & Feldplanung", border: "border-l-orange", nav: "turnier" },
      { icon: "bar-chart", name: "Statistiken", desc: "Auswertungen & Berichte", border: "border-l-blue", nav: "statistik" },
    ],
  },

  clubadmin: {
    id: "clubadmin",
    label: "Club Admin",
    subtitle: "TSV Hannover",
    userName: "Thomas Weber",
    initials: "TW",
    gradient: "from-green to-[#15803d]",
    defaultScreen: "dashboard",
    navSections: [
      {
        label: "",
        items: [
          { id: "dashboard", label: "Dashboard", icon: "grid" },
          { id: "mail", label: "Mail", icon: "mail" },
          { id: "kalender", label: "Kalender", icon: "calendar" },
          { id: "kontakte", label: "Kontakte", icon: "book-open" },
        ],
      },
      {
        label: "Mein Verein",
        items: [
          { id: "mannschaften", label: "Meine Mannschaften", icon: "users" },
          { id: "heimspieltermine", label: "Heimspieltermine", icon: "calendar-home" },
          { id: "spielplan", label: "Spielplan", icon: "calendar-edit" },
          { id: "vereins-mitglieder", label: "Mitglieder", icon: "star" },
          { id: "matchday-master", label: "MatchDay Master", icon: "shield-check" },
        ],
      },
      {
        label: "Verband",
        items: [
          { id: "alle-ligen", label: "Alle Ligen", icon: "org-tree" },
          { id: "alle-mannschaften", label: "Alle Mannschaften", icon: "layers" },
          { id: "statistik", label: "Statistiken", icon: "pie-chart" },
        ],
      },
      {
        label: "Verwaltung",
        items: [
          { id: "lizenz-uebersicht-spieler", label: "Lizenzen", icon: "clipboard" },
          { id: "rechnungen", label: "Rechnungen", badge: 1, icon: "file" },
          { id: "support-center", label: "Hilfe & Support", icon: "info" },
        ],
      },
    ],
    breadcrumbs: {
      dashboard: ["TSV Hannover", "Dashboard"],
      mail: ["TSV Hannover", "Mail"],
      kalender: ["TSV Hannover", "Kalender"],
      kontakte: ["TSV Hannover", "Kontakte"],
      mannschaften: ["TSV Hannover", "Meine Mannschaften"],
      "alle-ligen": ["TSV Hannover", "Alle Ligen"],
      "alle-mannschaften": ["TSV Hannover", "Alle Mannschaften"],
      spielplan: ["TSV Hannover", "Spielplan"],
      heimspieltermine: ["TSV Hannover", "Heimspieltermine"],
      statistik: ["TSV Hannover", "Statistiken"],
      rechnungen: ["TSV Hannover", "Rechnungen"],
      strafen: ["TSV Hannover", "Strafen"],
      "vereins-mitglieder": ["TSV Hannover", "Mitglieder"],
      "lizenz-uebersicht-spieler": ["TSV Hannover", "Lizenzen"],
    },
    newModalItems: [
      { icon: "users", name: "Mannschaft erstellen", desc: "Neues Team anlegen & melden", border: "border-l-green", nav: "mannschaften", action: "open-create" },
      { icon: "clipboard", name: "Spieler melden", desc: "Spielermeldung nach BSO §6.10", border: "border-l-accent", nav: "mannschaften", action: "open-create" },
      { icon: "refresh", name: "Vereinswechsel", desc: "Transfer beantragen nach BSO §8", border: "border-l-orange", nav: "mannschaften" },
      { icon: "calendar", name: "Spielplan ansehen", desc: "Nächste Spiele & Termine", border: "border-l-blue", nav: "spieltag" },
    ],
  },

  verbandsadmin: {
    id: "verbandsadmin",
    label: "Verbandsadmin",
    subtitle: "DVV",
    userName: "Dr. Claudia Meier",
    initials: "CM",
    gradient: "from-blue to-[#1d4ed8]",
    defaultScreen: "dashboard",
    navSections: [
      {
        label: "",
        items: [
          { id: "dashboard", label: "Dashboard", icon: "grid" },
          { id: "mail", label: "Mail", icon: "mail" },
          { id: "kalender", label: "Kalender", icon: "calendar" },
          { id: "kontakte", label: "Kontakte", icon: "book-open" },
        ],
      },
      {
        label: "Stammdaten",
        items: [
          { id: "organisationen", label: "Organisationen", icon: "org-tree" },
          { id: "personen", label: "Personen", icon: "users" },
          { id: "spielstaetten", label: "Spielstätten", icon: "map" },
          { id: "vereine", label: "Vereine", icon: "building" },
          { id: "rechte-rollen", label: "Rechte & Rollen", icon: "shield" },
          { id: "ehrungen", label: "Ehrungen", icon: "award" },
          { id: "spieler-self-service", label: "Spieler-Portal", icon: "user" },
        ],
      },
      {
        label: "Lizenzwesen",
        items: [
          { id: "lizenz-dashboard", label: "Lizenz-Dashboard", icon: "clipboard" },
          { id: "lizenz-queue", label: "Bearbeitungsqueue", badge: 8, icon: "list" },
          { id: "lizenz-config", label: "Lizenztypen", icon: "settings" },
        ],
      },
      {
        label: "Spielbetrieb",
        items: [
          { id: "liga-uebersicht", label: "Ligen", icon: "layers" },
          { id: "spieltag", label: "Spieltagsübersicht", icon: "scan" },
          { id: "spielplan-verwaltung", label: "Spielplan-Verwaltung", icon: "calendar-edit" },
          { id: "live-ticker", label: "Live-Ticker", icon: "volleyball" },
          { id: "beach-turniere", label: "Beach-Turniere", icon: "trophy" },
          { id: "spielanalyse", label: "Spielanalyse", icon: "pie-chart" },
          { id: "matchday-master", label: "MatchDay Master", icon: "shield-check" },
          { id: "sr-ansetzung", label: "SR-Ansetzungen", badge: 6, icon: "whistle" },
          { id: "sr-pool", label: "SR-Pool", icon: "star" },
          { id: "sr-fahrtkosten", label: "Fahrtkosten", icon: "edit" },
          { id: "spielbericht", label: "Spielbericht", icon: "clipboard" },
        ],
      },
      {
        label: "Finanzen & Organisation",
        items: [
          { id: "finanz-dashboard", label: "Finanzen", icon: "coin" },
          { id: "rechnungen", label: "Rechnungen", icon: "file" },
          { id: "strafen", label: "Strafbescheide", badge: 2, icon: "alert" },
          { id: "reporting", label: "Reporting", icon: "bar-chart" },
          { id: "automationen", label: "Automationen", icon: "zap" },
        ],
      },
      {
        label: "Social Media",
        items: [
          { id: "social-briefing", label: "Neues Briefing", icon: "megaphone" },
          { id: "social-review", label: "Content Review", icon: "newspaper" },
        ],
      },
      {
        label: "Analytics & KI",
        items: [
          { id: "dvv-analytics", label: "DVV Dashboard", icon: "pie-chart" },
          { id: "aeo-analytics", label: "AI Engine Optimization", icon: "zap" },
          { id: "web-performance", label: "Website Performance", icon: "bar-chart" },
          { id: "staffelplanung", label: "Staffelplanung", icon: "map" },
        ],
      },
      {
        label: "Kommunikation & Weiteres",
        items: [
          { id: "kommunikation", label: "Kommunikation", icon: "megaphone" },
          { id: "veranstaltungen", label: "Veranstaltungen", icon: "calendar-star" },
          { id: "cms", label: "CMS", icon: "newspaper" },
          { id: "lehrgaenge", label: "Lehrgänge", icon: "graduation-cap" },
          { id: "sponsoren", label: "Sponsoren", icon: "handshake" },
          { id: "shop", label: "Shop & Ausrüstung", icon: "shopping-bag" },
          { id: "support-center", label: "Hilfe & Support", icon: "info" },
        ],
      },
    ],
    breadcrumbs: {
      dashboard: ["DVV", "Dashboard"],
      mail: ["DVV", "Mail"],
      kalender: ["DVV", "Kalender"],
      kontakte: ["DVV", "Kontakte"],
      organisationen: ["DVV", "Stammdaten", "Organisationen"],
      personen: ["DVV", "Stammdaten", "Personen"],
      spielstaetten: ["DVV", "Stammdaten", "Spielstätten"],
      "rechte-rollen": ["DVV", "Stammdaten", "Rechte & Rollen"],
      ehrungen: ["DVV", "Stammdaten", "Ehrungen"],
      "lizenz-dashboard": ["DVV", "Lizenzwesen", "Dashboard"],
      "lizenz-queue": ["DVV", "Lizenzwesen", "Bearbeitungsqueue"],
      "lizenz-config": ["DVV", "Lizenzwesen", "Lizenztypen"],
      "liga-uebersicht": ["DVV", "Spielbetrieb", "Ligen"],
      "spielplan-verwaltung": ["DVV", "Spielbetrieb", "Spielplan-Verwaltung"],
      "live-ticker": ["DVV", "Spielbetrieb", "Live-Ticker"],
      "beach-turniere": ["DVV", "Spielbetrieb", "Beach-Turniere"],
      spielanalyse: ["DVV", "Spielbetrieb", "Spielanalyse"],
      "match-detail": ["DVV", "Spielbetrieb", "Live-Ticker", "Spiel-Detail"],
      "finanz-dashboard": ["DVV", "Finanzen", "Dashboard"],
      automationen: ["DVV", "Organisation", "Automationen"],
      reporting: ["DVV", "Organisation", "Reporting"],
      "sr-ansetzung": ["DVV", "Spielbetrieb", "SR-Ansetzungen"],
      "sr-pool": ["DVV", "Spielbetrieb", "SR-Pool"],
      "sr-fahrtkosten": ["DVV", "Spielbetrieb", "Fahrtkosten"],
      kommunikation: ["DVV", "Kommunikation & Weiteres", "Hub"],
      lehrgaenge: ["DVV", "Kommunikation & Weiteres", "Lehrgänge"],
      sponsoren: ["DVV", "Kommunikation & Weiteres", "Sponsoren"],
      shop: ["DVV", "Kommunikation & Weiteres", "Shop & Ausrüstung"],
      "alle-ligen": ["DVV", "Alle Ligen"],
      "alle-mannschaften": ["DVV", "Alle Mannschaften"],
      vereine: ["DVV", "Vereine"],
      spieltag: ["DVV", "Spielbetrieb", "Spieltagsübersicht"],
      heimspieltermine: ["DVV", "Heimspieltermine"],
      statistik: ["DVV", "Statistiken"],
      veranstaltungen: ["DVV", "Veranstaltungen"],
      veranstaltung: ["DVV", "Veranstaltung erstellen"],
      rechnungen: ["DVV", "Rechnungen"],
      strafen: ["DVV", "Strafbescheide"],
      "aeo-analytics": ["DVV", "Analytics & KI", "AI Engine Optimization"],
      "web-performance": ["DVV", "Analytics & KI", "Website Performance"],
      staffelplanung: ["DVV", "Analytics & KI", "Staffelplanung"],
      spielbericht: ["DVV", "Spielbetrieb", "Spielbericht"],
      "spieler-self-service": ["DVV", "Stammdaten", "Spieler-Portal"],
      "social-briefing": ["DVV", "Social Media", "Neues Briefing"],
      "social-review": ["DVV", "Social Media", "Content Review"],
      "dvv-analytics": ["DVV", "Analytics & KI", "DVV Dashboard"],
      "matchday-master": ["DVV", "Spielbetrieb", "MatchDay Master"],
      "support-center": ["DVV", "Hilfe & Support"],
    },
    newModalItems: [
      { icon: "trophy", name: "Veranstaltung erstellen", desc: "Turnier, Lehrgang, Versammlung", border: "border-l-accent", nav: "veranstaltung" },
      { icon: "clipboard", name: "Lizenz bearbeiten", desc: "Lizenzanträge prüfen & freigeben", border: "border-l-green", nav: "lizenz-queue" },
      { icon: "coin", name: "Strafbescheid", desc: "Ordnungsstrafe nach BSO §17", border: "border-l-red", nav: "strafen", action: "open-strafe" },
      { icon: "newspaper", name: "Inhalt erstellen", desc: "CMS Block-Editor & KI-Assistent", border: "border-l-blue", nav: "cms" },
    ],
  },

  benutzer: {
    id: "benutzer",
    label: "Spieler",
    subtitle: "TSV Blau-Weiss Berlin",
    userName: "Max Keller",
    initials: "MK",
    gradient: "from-orange to-[#d97706]",
    defaultScreen: "spieler-self-service",
    navSections: [
      {
        label: "",
        items: [
          { id: "spieler-self-service", label: "Mein Bereich", icon: "home" },
          { id: "kalender", label: "Mein Kalender", icon: "calendar" },
          { id: "mail", label: "Meine Nachrichten", icon: "mail" },
        ],
      },
      {
        label: "Mein Sport",
        items: [
          { id: "mannschaften", label: "Meine Mannschaften", icon: "users" },
          { id: "spielplan", label: "Mein Spielplan", icon: "calendar-edit" },
          { id: "live-ticker", label: "Ergebnisse & Tabelle", icon: "volleyball" },
          { id: "statistik", label: "Meine Statistiken", icon: "pie-chart" },
        ],
      },
      {
        label: "Meine Lizenzen",
        items: [
          { id: "lizenz-uebersicht-spieler", label: "Lizenzen & Status", icon: "shield" },
          { id: "veranstaltungen", label: "Lehrgange & Veranstaltungen", icon: "calendar-star" },
          { id: "support-center", label: "Hilfe & Support", icon: "info" },
        ],
      },
    ],
    breadcrumbs: {
      "spieler-self-service": ["Mein Bereich", "Ubersicht"],
      kalender: ["Mein Bereich", "Mein Kalender"],
      mail: ["Mein Bereich", "Meine Nachrichten"],
      mannschaften: ["Mein Sport", "Meine Mannschaften"],
      spielplan: ["Mein Sport", "Mein Spielplan"],
      "live-ticker": ["Mein Sport", "Ergebnisse & Tabelle"],
      statistik: ["Mein Sport", "Meine Statistiken"],
      "lizenz-uebersicht-spieler": ["Meine Lizenzen", "Lizenzen & Status"],
      veranstaltungen: ["Meine Lizenzen", "Lehrgange & Veranstaltungen"],
    },
    newModalItems: [
      { icon: "shield", name: "Lizenz verlangern", desc: "Hallelizenz oder Beach-Lizenz erneuern", border: "border-l-green", nav: "lizenz-uebersicht-spieler" },
      { icon: "calendar-star", name: "Veranstaltung anmelden", desc: "Lehrgange & Events", border: "border-l-accent", nav: "veranstaltungen" },
    ],
  },

  socialmedia: {
    id: "socialmedia",
    label: "Social Media Manager",
    subtitle: "DVV Kommunikation",
    userName: "Julia Hartmann",
    initials: "JH",
    gradient: "from-[#ec4899] to-[#be185d]",
    defaultScreen: "social-briefing",
    navSections: [
      {
        label: "",
        items: [
          { id: "dashboard", label: "Dashboard", icon: "home" },
          { id: "mail", label: "Mail", icon: "mail" },
          { id: "kalender", label: "Kalender", icon: "calendar" },
        ],
      },
      {
        label: "Content & Kampagnen",
        items: [
          { id: "social-briefing", label: "Neues Briefing", icon: "megaphone" },
          { id: "social-review", label: "Content Review", icon: "newspaper" },
          { id: "cms", label: "CMS & Website", icon: "newspaper" },
          { id: "kommunikation", label: "Rundschreiben", icon: "mail" },
        ],
      },
      {
        label: "Analytics",
        items: [
          { id: "aeo-analytics", label: "AI Engine Optimization", icon: "zap" },
          { id: "web-performance", label: "Website Performance", icon: "bar-chart" },
          { id: "dvv-analytics", label: "DVV Dashboard", icon: "pie-chart" },
        ],
      },
      {
        label: "Medien",
        items: [
          { id: "veranstaltungen", label: "Veranstaltungen", icon: "calendar-star" },
          { id: "sponsoren", label: "Sponsoren & Partner", icon: "handshake" },
          { id: "lehrgaenge", label: "Presse & Medien", icon: "file" },
          { id: "support-center", label: "Hilfe & Support", icon: "info" },
        ],
      },
    ],
    breadcrumbs: {
      dashboard: ["DVV", "Dashboard"],
      mail: ["DVV", "Mail"],
      kalender: ["DVV", "Kalender"],
      "social-briefing": ["Content", "Neues Briefing"],
      "social-review": ["Content", "Content Review"],
      cms: ["Content", "CMS & Website"],
      kommunikation: ["Content", "Rundschreiben"],
      "aeo-analytics": ["Analytics", "AI Engine Optimization"],
      "web-performance": ["Analytics", "Website Performance"],
      "dvv-analytics": ["Analytics", "DVV Dashboard"],
      veranstaltungen: ["Medien", "Veranstaltungen"],
      sponsoren: ["Medien", "Sponsoren"],
      lehrgaenge: ["Medien", "Presse & Medien"],
    },
    newModalItems: [
      { icon: "megaphone", name: "Neues Briefing", desc: "KI-gestutztes Social Media Briefing", border: "border-l-accent", nav: "social-briefing" },
      { icon: "newspaper", name: "Content prufen", desc: "Generierte Inhalte reviewen & exportieren", border: "border-l-green", nav: "social-review" },
      { icon: "mail", name: "Rundschreiben", desc: "Verband-weite Kommunikation", border: "border-l-blue", nav: "kommunikation" },
    ],
  },
};
