import type { Role, RoleConfig } from "@/types/roles";

export const roleConfigs: Record<Role, RoleConfig> = {
  staffelleitung: {
    id: "staffelleitung",
    label: "Staffelleitung",
    subtitle: "DVV · Verbandsliga Nord",
    userName: "Stefan Meier",
    initials: "SM",
    gradient: "from-accent to-[#6D28D9]",
    defaultScreen: "dashboard",
    navSections: [
      {
        label: "",
        items: [
          { id: "dashboard", label: "Dashboard", badge: 5, icon: "grid" },
          { id: "mail", label: "Mail", icon: "mail" },
          { id: "kalender", label: "Kalender", icon: "calendar" },
          { id: "kontakte", label: "Kontakte", icon: "book-open" },
        ],
      },
      {
        label: "Spielbetrieb",
        items: [
          { id: "spieltag", label: "Ligenübersicht", badge: 2, icon: "calendar-edit" },
          { id: "ligen", label: "Meine Ligen", icon: "star" },
          { id: "mannschaft", label: "Mannschaften meiner Ligen", icon: "users" },
          { id: "heimspieltermine", label: "Heimspieltermine", icon: "calendar-home" },
          { id: "spielplan-verwaltung", label: "Spielplan", icon: "calendar-edit" },
          { id: "live-ticker", label: "Live-Ticker", icon: "volleyball" },
        ],
      },
      {
        label: "Verband",
        items: [
          { id: "alle-ligen", label: "Alle Ligen", icon: "org-tree" },
          { id: "alle-mannschaften", label: "Alle Mannschaften", icon: "users" },
          { id: "statistik", label: "Statistiken", icon: "pie-chart" },
          { id: "strafen", label: "Meine Strafbescheide", badge: 1, icon: "alert" },
        ],
      },
      {
        label: "Schiedsrichter",
        items: [
          { id: "sr-ansetzung", label: "SR-Ansetzungen", badge: 3, icon: "whistle" },
        ],
      },
    ],
    breadcrumbs: {
      dashboard: ["DVV", "Dashboard"],
      mail: ["DVV", "Mail"],
      kalender: ["DVV", "Kalender"],
      kontakte: ["DVV", "Kontakte"],
      ligen: ["DVV", "Meine Ligen"],
      mannschaft: ["DVV", "Mannschaften meiner Ligen"],
      "alle-ligen": ["DVV", "Alle Ligen"],
      "alle-mannschaften": ["DVV", "Alle Mannschaften"],
      spieltag: ["DVV", "Ligenübersicht"],
      heimspieltermine: ["DVV", "Heimspieltermine"],
      statistik: ["DVV", "Statistiken"],
      veranstaltungen: ["DVV", "Veranstaltungen"],
      veranstaltung: ["DVV", "Veranstaltung erstellen"],
      rechnungen: ["DVV", "Rechnungen"],
      strafen: ["DVV", "Meine Strafbescheide"],
      "spielplan-verwaltung": ["DVV", "Spielplan-Verwaltung"],
      "live-ticker": ["DVV", "Live-Ticker"],
      "sr-ansetzung": ["DVV", "SR-Ansetzungen"],
    },
    newModalItems: [
      { icon: "calendar", name: "Spieltag verwalten", desc: "Spielplan bearbeiten, Verlegungen", border: "border-l-accent", nav: "spieltag" },
      { icon: "clipboard", name: "Mannschaftsmeldung", desc: "Meldungen prüfen & bestätigen", border: "border-l-green", nav: "mannschaft", action: "open-neue-meldung" },
      { icon: "volleyball", name: "Turnier erstellen", desc: "Turnierbaum & Feldplanung", border: "border-l-orange", nav: "turnier" },
      { icon: "bar-chart", name: "Statistiken", desc: "Auswertungen & Berichte", border: "border-l-blue", nav: "statistik" },
    ],
  },

  clubadmin: {
    id: "clubadmin",
    label: "Club Admin",
    subtitle: "TSV Hannover",
    userName: "Thomas Weber",
    initials: "TW",
    gradient: "from-green to-[#15803d]",
    defaultScreen: "dashboard",
    navSections: [
      {
        label: "",
        items: [
          { id: "dashboard", label: "Dashboard", badge: 3, icon: "grid" },
          { id: "mail", label: "Mail", icon: "mail" },
          { id: "kalender", label: "Kalender", icon: "calendar" },
          { id: "kontakte", label: "Kontakte", icon: "book-open" },
        ],
      },
      {
        label: "Mein Verein",
        items: [
          { id: "mannschaften", label: "Meine Mannschaften", icon: "users" },
          { id: "heimspieltermine", label: "Heimspieltermine", icon: "calendar-home" },
          { id: "spielplan", label: "Spielplan", icon: "calendar-edit" },
          { id: "vereins-mitglieder", label: "Mitglieder", icon: "users" },
        ],
      },
      {
        label: "Lizenzen",
        items: [
          { id: "lizenz-uebersicht-spieler", label: "Lizenzen", icon: "clipboard" },
        ],
      },
      {
        label: "Verband",
        items: [
          { id: "alle-ligen", label: "Alle Ligen", icon: "org-tree" },
          { id: "alle-mannschaften", label: "Alle Mannschaften", icon: "users" },
          { id: "statistik", label: "Statistiken", icon: "pie-chart" },
        ],
      },
      {
        label: "Finanzen",
        items: [
          { id: "rechnungen", label: "Rechnungen", badge: 1, icon: "file" },
        ],
      },
    ],
    breadcrumbs: {
      dashboard: ["TSV Hannover", "Dashboard"],
      mail: ["TSV Hannover", "Mail"],
      kalender: ["TSV Hannover", "Kalender"],
      kontakte: ["TSV Hannover", "Kontakte"],
      mannschaften: ["TSV Hannover", "Meine Mannschaften"],
      "alle-ligen": ["TSV Hannover", "Alle Ligen"],
      "alle-mannschaften": ["TSV Hannover", "Alle Mannschaften"],
      spielplan: ["TSV Hannover", "Spielplan"],
      heimspieltermine: ["TSV Hannover", "Heimspieltermine"],
      statistik: ["TSV Hannover", "Statistiken"],
      rechnungen: ["TSV Hannover", "Rechnungen"],
      strafen: ["TSV Hannover", "Strafen"],
      "vereins-mitglieder": ["TSV Hannover", "Mitglieder"],
      "lizenz-uebersicht-spieler": ["TSV Hannover", "Lizenzen"],
    },
    newModalItems: [
      { icon: "users", name: "Mannschaft erstellen", desc: "Neues Team anlegen & melden", border: "border-l-green", nav: "mannschaften", action: "open-create" },
      { icon: "clipboard", name: "Spieler melden", desc: "Spielermeldung nach BSO §6.10", border: "border-l-accent", nav: "mannschaften", action: "open-create" },
      { icon: "refresh", name: "Vereinswechsel", desc: "Transfer beantragen nach BSO §8", border: "border-l-orange", nav: "mannschaften" },
      { icon: "calendar", name: "Spielplan ansehen", desc: "Nächste Spiele & Termine", border: "border-l-blue", nav: "spieltag" },
    ],
  },

  verbandsadmin: {
    id: "verbandsadmin",
    label: "Verbandsadmin",
    subtitle: "DVV",
    userName: "Dr. Claudia Meier",
    initials: "CM",
    gradient: "from-blue to-[#1d4ed8]",
    defaultScreen: "dashboard",
    navSections: [
      {
        label: "",
        items: [
          { id: "dashboard", label: "Dashboard", badge: 8, icon: "grid" },
          { id: "mail", label: "Mail", icon: "mail" },
          { id: "kalender", label: "Kalender", icon: "calendar" },
          { id: "kontakte", label: "Kontakte", icon: "book-open" },
        ],
      },
      {
        label: "Stammdaten",
        items: [
          { id: "organisationen", label: "Organisationen", icon: "org-tree" },
          { id: "personen", label: "Personen", badge: 3, icon: "users" },
          { id: "spielstaetten", label: "Spielstätten", icon: "map" },
          { id: "vereine", label: "Vereine", icon: "building" },
          { id: "rechte-rollen", label: "Rechte & Rollen", icon: "key" },
          { id: "ehrungen", label: "Ehrungen", icon: "award" },
        ],
      },
      {
        label: "Lizenzwesen",
        items: [
          { id: "lizenz-dashboard", label: "Lizenz-Dashboard", badge: 12, icon: "clipboard" },
          { id: "lizenz-queue", label: "Bearbeitungsqueue", badge: 8, icon: "list" },
          { id: "lizenz-config", label: "Lizenztypen", icon: "settings" },
        ],
      },
      {
        label: "Spielbetrieb",
        items: [
          { id: "liga-uebersicht", label: "Liga-Übersicht", icon: "layers" },
          { id: "spielplan-verwaltung", label: "Spielplan-Verwaltung", icon: "calendar-edit" },
          { id: "spieltag", label: "Ligenübersicht", badge: 2, icon: "calendar-edit" },
          { id: "live-ticker", label: "Live-Ticker", icon: "volleyball" },
          { id: "beach-turniere", label: "Beach-Turniere", icon: "trophy" },
          { id: "spielanalyse", label: "Spielanalyse", icon: "bar-chart" },
        ],
      },
      {
        label: "Finanzen & Organisation",
        items: [
          { id: "finanz-dashboard", label: "Finanzen", badge: 5, icon: "coin" },
          { id: "rechnungen", label: "Rechnungen", icon: "file" },
          { id: "automationen", label: "Automationen", icon: "zap" },
          { id: "reporting", label: "Reporting", icon: "bar-chart" },
          { id: "strafen", label: "Strafbescheide", badge: 2, icon: "alert" },
        ],
      },
      {
        label: "Schiedsrichter",
        items: [
          { id: "sr-ansetzung", label: "SR-Ansetzungen", badge: 6, icon: "whistle" },
          { id: "sr-pool", label: "SR-Pool", icon: "users" },
          { id: "sr-fahrtkosten", label: "Fahrtkosten", icon: "coin" },
        ],
      },
      {
        label: "Kommunikation",
        items: [
          { id: "kommunikation", label: "Kommunikation", icon: "megaphone" },
          { id: "veranstaltungen", label: "Veranstaltungen", icon: "calendar-star" },
          { id: "cms", label: "CMS", icon: "newspaper" },
        ],
      },
      {
        label: "Bildung & Sponsoring",
        items: [
          { id: "lehrgaenge", label: "Lehrgänge", icon: "graduation-cap" },
          { id: "sponsoren", label: "Sponsoren", icon: "handshake" },
          { id: "shop", label: "Shop & Ausrüstung", icon: "shopping-bag" },
        ],
      },
    ],
    breadcrumbs: {
      dashboard: ["DVV", "Dashboard"],
      mail: ["DVV", "Mail"],
      kalender: ["DVV", "Kalender"],
      kontakte: ["DVV", "Kontakte"],
      organisationen: ["DVV", "Stammdaten", "Organisationen"],
      personen: ["DVV", "Stammdaten", "Personen"],
      spielstaetten: ["DVV", "Stammdaten", "Spielstätten"],
      "rechte-rollen": ["DVV", "Stammdaten", "Rechte & Rollen"],
      ehrungen: ["DVV", "Stammdaten", "Ehrungen"],
      "lizenz-dashboard": ["DVV", "Lizenzwesen", "Dashboard"],
      "lizenz-queue": ["DVV", "Lizenzwesen", "Bearbeitungsqueue"],
      "lizenz-config": ["DVV", "Lizenzwesen", "Lizenztypen"],
      "liga-uebersicht": ["DVV", "Spielbetrieb", "Liga-Übersicht"],
      "spielplan-verwaltung": ["DVV", "Spielbetrieb", "Spielplan-Verwaltung"],
      "live-ticker": ["DVV", "Spielbetrieb", "Live-Ticker"],
      "beach-turniere": ["DVV", "Spielbetrieb", "Beach-Turniere"],
      spielanalyse: ["DVV", "Spielbetrieb", "Spielanalyse"],
      "finanz-dashboard": ["DVV", "Finanzen", "Dashboard"],
      automationen: ["DVV", "Organisation", "Automationen"],
      reporting: ["DVV", "Organisation", "Reporting"],
      "sr-ansetzung": ["DVV", "Schiedsrichter", "Ansetzungen"],
      "sr-pool": ["DVV", "Schiedsrichter", "SR-Pool"],
      "sr-fahrtkosten": ["DVV", "Schiedsrichter", "Fahrtkosten"],
      kommunikation: ["DVV", "Kommunikation", "Hub"],
      lehrgaenge: ["DVV", "Bildung", "Lehrgänge"],
      sponsoren: ["DVV", "Sponsoring", "Übersicht"],
      shop: ["DVV", "Shop & Ausrüstung"],
      "alle-ligen": ["DVV", "Alle Ligen"],
      "alle-mannschaften": ["DVV", "Alle Mannschaften"],
      vereine: ["DVV", "Vereine"],
      spieltag: ["DVV", "Ligenübersicht"],
      heimspieltermine: ["DVV", "Heimspieltermine"],
      statistik: ["DVV", "Statistiken"],
      veranstaltungen: ["DVV", "Veranstaltungen"],
      veranstaltung: ["DVV", "Veranstaltung erstellen"],
      rechnungen: ["DVV", "Rechnungen"],
      strafen: ["DVV", "Strafbescheide"],
    },
    newModalItems: [
      { icon: "trophy", name: "Veranstaltung erstellen", desc: "Turnier, Lehrgang, Versammlung", border: "border-l-accent", nav: "veranstaltung" },
      { icon: "clipboard", name: "Lizenz bearbeiten", desc: "Lizenzanträge prüfen & freigeben", border: "border-l-green", nav: "lizenz-queue" },
      { icon: "coin", name: "Strafbescheid", desc: "Ordnungsstrafe nach BSO §17", border: "border-l-red", nav: "strafen", action: "open-strafe" },
      { icon: "newspaper", name: "Inhalt erstellen", desc: "CMS Block-Editor & KI-Assistent", border: "border-l-blue", nav: "cms" },
    ],
  },
};
